name: Release (semantic-release)

on:
  push:
    branches: [ master ]

permissions:
  contents: write

jobs:
  semantic_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # Use the bot token for pushes
          token: ${{ secrets.GH_BOT_TOKEN }}

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - run: pip install python-semantic-release

      - name: Configure git identity (optional but nice)
        run: |
          git config user.name "goaziz"
          git config user.email "azizgaybullaev@mail.ru"

      - name: Semantic Release
        env:
          GH_TOKEN: ${{ secrets.GH_BOT_TOKEN }}   # for API calls
        run: semantic-release version --push --vcs-release
